
export const SUBMIT_QUIZ = 'SUBMIT_QUIZ';
export const CALCULATE_SCORE = 'CALCULATE_SCORE';
export const RESET_QUIZ = 'RESET_QUIZ';
export const SET_USERNAME = 'SET_USERNAME';
export const UPDATE_DESCRIPTIVE_ANSWER = 'UPDATE_DESCRIPTIVE_ANSWER'